services:
  - type: web
    name: wycinacz
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/wycinacz-1.0.0.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m
